### ISSUE TITLE
Listagem de movimentações da conta

### ISSUE THREAD

**Issue by pabloxavier** [pabloxavier/fakebank#106]
Endpoint:
```javascript
GET /contas/{codigoConta}/movimentacoes
```

Saída:
```javascript
{
    content:
    [
        {
            codigo: 123,
            data: 2015-10-14 15:56,
            valor: 400.00,
            tipo: {
                codigo: 123,
                tipo: "Saque",
                operacao: "Debito"
            },
            saldoAnterior: 1000.00,
            saldoFinal: 600.00
        }
    ]
}
```

**Comment by MateusAbdala** [comment]
O endPoint:

**GET** /contas/{codigoConta}/movimentacoes
foge um pouco do padrão utilizado em movimentações.
Minha Sugestão:

**GET** /movimentacoes/{codigoConta}

**Comment by MateusAbdala** [comment]
ou uma opção que já é esperada pela aplicação:
**GET** /movimentacoes/pesquisa?conta=12345

**Comment by pabloxavier** [comment]
Oba

Acredito que dentre as sugestões, a mais aceitável seria:
**GET** /movimentacoes/contas/{codigoConta}

A sugestão abaixo, sugere uma consulta de movimentação pelo ID da movimentação
**GET** /movimentacoes/{codigoConta}

... e colocar na queryString não é lá muito "bonito" (acredito eu)

Abs

**Comment by pabloxavier** [comment]
@MateusAbdala, @JuhBazilewitz e @leonardovalladao favor validar.

**Comment by JuhBazilewitz** [comment]
Faremos esse endpoint então

**GET** /movimentacoes/contas/{codigoConta}
