### ISSUE TITLE
Allowed Methods

### ISSUE THREAD

**Issue by MateusAbdala** [pabloxavier/fakebank#87]
Percebi que em **WebConfiguration** possui o seguinte **CorsMapping**:

```
public void addCorsMappings(CorsRegistry registry) {
	registry
		.addMapping("/**")
		.allowedMethods("GET", "POST", "PUT", "DELETE", "OPTIONS", "HEAD", "TRACE", "CONNECT")
		.allowedHeaders("*")
		.maxAge(3600);
}
```
e permite requisições **HEAD**, **TRACE** e **CONNECT**, porquê?
e porque o **PATCH** não foi adicionado?

**Comment by pabloxavier** [comment]
@MateusAbdala Foi apenas um exemplo.
Só para mostrar mesmo.
🤓

**Comment by CaetanoYunesVieira** [comment]
Deixa de ser implicante, @MateusAbdala.
